### ISSUE TITLE
whl file for mytransformers library

### ISSUE THREAD

**Issue by ucalyptus2** [Doby-Xu/ST#1]
@Doby-Xu

**Comment by Doby-Xu** [comment]
So sorry that I missed the email of this issue from github and it took me so long to notice this issue.

I'll soon update the repo to include the modified BERT and GPT-2 model codes

**Comment by rujiangyouyou** [comment]
waiting for the update 👀

**Comment by Doby-Xu** [comment]
So sorry for the delay.

I've pushed the `modeling_bert.py` and `modeling_gpt2.py`, the modification made in `mytransformer`. And you can follow the readme file in `ShowCase/Bert_GPT2`.

And I apologize for my poor code engineering.  I would refine the directory structure of this repo soon.
